name: Nitro Chat Smoke Test

on:
  schedule:
    - cron: '30 0 */3 * *'
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/Nitro_Chat/smoke_test.cy.js
